version: '3'
services:
#Service apache toma el Dockerfile del directorio ./apache
 wordpress:
  build: ./wordpress
#Mapeo de puerto 8082 del host al 80 del container
  ports:
  - "8082:80"
  hostname: wordpress
#Mapea el volumen apache_data al directorio de datos de apache
  volumes:
  - apache_data:/var/www/html
  - mariadb_data:/var/lib/mysql
volumes:
  apache_data:
  mariadb_data:
